name: Build Mod on Push

on:
  push:

jobs:

  build:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: windows-latest

    steps:
    - name: Build
      id: build-action
      uses: xADDBx/BuildOwlcatMod@v2
      with:
        GAME_NAME: Wrath
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_NAME: ${{ github.repository_owner }}
        PACKAGE_OWNER: xADDBx
        DEPENDENCY_LINKS: "https://github.com/Vek17/TabletopTweaks-Core/releases/latest/download/TabletopTweaks-Core.zip"
        DEPENDENCY_NAMES: "Mods\\TabletopTweaks-Core\\"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.zipFile }}
        path: ${{ env.outDir }}
