name: Create Release for new Tag

on:
  push:
    tags:        
      - '**'

jobs:

  build:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: read

    steps:
    - name: Build
      id: build-action
      uses: xADDBx/BuildOwlcatMod@v2
      with:
        GAME_NAME: Wrath
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_NAME: ${{ github.repository_owner }}
        PACKAGE_OWNER: xADDBx
        DEPENDENCY_LINKS: "https://github.com/Vek17/TabletopTweaks-Core/releases/latest/download/TabletopTweaks-Core.zip"
        DEPENDENCY_NAMES: "Mods\\TabletopTweaks-Core\\"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.zipFile }}
        path: ${{ env.outDir }}
    
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ env.zipFilePath }}\*.zip
        name: ${{ env.ZipFile }} built for Wrath ${{ env.gameVersionNum }}${{ env.gameVersionSuffix }}